---

- name: Add Nginx repository
  become: yes
  apt_repository:
    repo: ppa:nginx/stable
    state: present
    validate_certs: no

- name: Ensure latest nginx and supporting packages are installed
  become: yes
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - "{{ 'nginx=' + sansible_nginx_version if sansible_nginx_version else 'nginx' }}"
    - "{{ 'nginx-extras=' + sansible_nginx_version if sansible_nginx_version else 'nginx-extras' }}"

- name: Ensure includes folder exists
  become: yes
  file:
    name: /etc/nginx/includes
    owner: root
    group: root
    state: directory

- name: Check for existence of logrotate config
  become: yes
  stat:
    path: /etc/logrotate.d/nginx
  register: sansible_nginx_logrotate_check

- name: Fix logrotate config if required
  become: yes
  lineinfile:
    backrefs: yes
    dest: /etc/logrotate.d/nginx
    line: '		service nginx reload >/dev/null 2>&1'
    regexp: 'invoke-rc.d nginx rotate >\/dev\/null 2>&1'
  when: sansible_nginx_logrotate_check.stat.exists
