---

- name: Configure nginx service
  become: yes
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nginx

- name: Removes default site
  become: yes
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
    - reload nginx

- name: Configure nginx status include
  become: yes
  template:
    src: includes/nginx_status.j2
    dest: /etc/nginx/includes/nginx_status
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nginx
