---

driver:
  name: docker

platforms:
  - name: sansible_nginx-trusty
    image: ubuntu:trusty
  - name: sansible_nginx-xenial
    image: ubuntu:xenial
# Currently not supported by PPA
#  - name: sansible_nginx-bionic
#    image: ubuntu:bionic

provisioner:
  name: ansible
  lint:
    name: ansible-lint

lint:
  name: yamllint
  options:
    config-data:
      extends: default
      ignore: .venv_ansible*
      rules:
        line-length:
          max: 159
        truthy: disable

dependency:
  name: galaxy
  options:
    role-file: requirements.yml

scenario:
  name: default

verifier:
  name: testinfra
  lint:
    name: flake8
